---
title: 'Lab #5'
author: "Jay Maxwell"
output: html_document
---
<h4>DS202</h4>
<h4>Fall 2020</h4>
<hr>
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)

```

1. Are there some days of the week where more accidents happen than the others (see FARS manual, use variable DAY_WEEK)?
2. Create a data frame containing the persons who are fatally hurt in the accidents (look up variable INJ_SEV)
3. Create a data frame containing the most dangerous vehicle make in each state. The number of persons fatally hit in the vehicle make is used to assess the (non-)safety of a make. Make sure to handle the missing values appropriately. (look up variable MAKE)
4. Create a map, and label each state with the most dangerous vehicle. Discuss the definition of the most dangerous vehicle, and what you find from the map. (Hint: Read the description for the STATE and COUNTY columns in the FARS manual. The state & county codes are Geographic Locator Codes (GLCs) from the General Services Administration’s (GSA) publication. Use readxl::read_xlsx to read in the GLCs.)
5. Join the accident and person table (work out which variable(s) to use)
6. Tally the number of accidents by day of the week (DAY_WEEK), hour of the day (HOUR) and gender (SEX). Visualize the results.
7. Now plot a choropleth map of the number of deaths on a county level.
8. Is summer or winter more dangerous? Does this depend on states? Explore and explain.